/*
 * Copyright 2020-2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 0.9.6
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "board.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitLpuartPins();
#if defined(WIFI_ENABLED)
    BOARD_InitWiFiPins();
#endif
#if defined(ENABLE_INPUT_DEV_PdmMic)
    BOARD_InitMicPins();
#endif /* ENABLE_INPUT_DEV_PdmMic */
#if defined(ENABLE_OUTPUT_DEV_MqsAudio) || defined(ENABLE_OUTPUT_DEV_MqsStreamerAudio)
    BOARD_InitMqsPins();
#endif /* ENABLE_OUTPUT_DEV_MqsAudio */
    BOARD_InitFlexioCameraPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLpuartPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: M15, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AD_25, software_input_on: Enable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Disable, drive_strength: Normal, slew_rate: Slow}
  - {pin_num: L13, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AD_24, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper, open_drain: Disable, drive_strength: Normal,
    slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLpuartPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLpuartPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

#if DEBUG_CONSOLE_UART_INDEX == 1
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 is configured as LPUART1_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 is configured as LPUART1_RXD */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_25 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 PAD functional properties : */
      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 PAD functional properties : */
      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
#elif DEBUG_CONSOLE_UART_INDEX == 12
  IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_00_LPUART12_TXD, /* GPIO_LPSR_00 is configured as LPUART12_TXD */
                   0U); /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_01_LPUART12_RXD, /* GPIO_LPSR_01 is configured as LPUART12_RXD */
                   1U);                              /* Software Input On Field: Force input path of pad GPIO_AD_25 */
#endif
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMicPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitMicPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_08_MIC_CLK,            /* GPIO_LPSR_08 is configured as MIC_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_09_MIC_BITSTREAM0,     /* GPIO_LPSR_09 is configured as MIC_BITSTREAM0 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */

  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_08_MIC_CLK,            /* GPIO_LPSR_08 PAD functional properties : */
      0x00U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: normal driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_09_MIC_BITSTREAM0,     /* GPIO_LPSR_09 PAD functional properties : */
      0x03U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain LPSR Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitWiFiPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitWiFiPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */


  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_34_GPIO10_IO01,          /* GPIO_AD_34 is configured as GPIO10_IO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_35_GPIO10_IO02,          /* GPIO_AD_35 is configured as GPIO10_IO02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 is configured as USDHC1_CMD */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_00 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 is configured as USDHC1_CLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_01 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 is configured as USDHC1_DATA0 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_02 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 is configured as USDHC1_DATA1 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_03 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 is configured as USDHC1_DATA2 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_04 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 is configured as USDHC1_DATA3 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_05 */

  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 PAD functional properties : */
      0x0CU);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: No Pull
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high drive strength
                                                 Pull Down Pull Up Field: Internal pullup resistor enabled
                                                 Open Drain Field: Disabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */

  gpio_pin_config_t pinConfig = {
      .direction   = kGPIO_DigitalOutput,
      .outputLogic = 0,
  };

  GPIO_PinInit(BOARD_WIFI_AWAM510_WLAN_ENABLE_GPIO, BOARD_WIFI_AWAM510_WLAN_ENABLE_PIN, &pinConfig);
  GPIO_PinInit(BOARD_WIFI_AWAM510_BT_ENABLE_GPIO, BOARD_WIFI_AWAM510_BT_ENABLE_PIN, &pinConfig);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMQSPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitMqsPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

    /* GPIO configuration of AUDIO_CD on GPIO_EMC_B2_19 (pin U2) */
    gpio_pin_config_t AUDIO_CD_config = {
        .direction = kGPIO_DigitalOutput,
        .outputLogic = 0U,
        .interruptMode = kGPIO_NoIntmode
    };
    /* Initialize GPIO functionality on GPIO_EMC_B2_19 (pin U2) */
    GPIO_PinInit(GPIO2, 29U, &AUDIO_CD_config);

    IOMUXC_SetPinMux(
        IOMUXC_GPIO_EMC_B1_40_MQS_RIGHT,        /* GPIO_EMC_B1_40 is configured as MQS_RIGHT */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(
        IOMUXC_GPIO_EMC_B1_41_MQS_LEFT,         /* GPIO_EMC_B1_41 is configured as MQS_LEFT */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(
        IOMUXC_GPIO_EMC_B2_19_GPIO_MUX2_IO29,   /* GPIO_EMC_B2_19 is configured as GPIO_MUX2_IO29 */
        0U);                                    /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_GPR->GPR41 = ((IOMUXC_GPR->GPR41 &
      (~(IOMUXC_GPR_GPR41_GPIO_MUX2_GPIO_SEL_HIGH_MASK))) /* Mask bits to zero which are setting */
        | IOMUXC_GPR_GPR41_GPIO_MUX2_GPIO_SEL_HIGH(0x00U) /* GPIO2 and CM7_GPIO2 share same IO MUX function, GPIO_MUX2 selects one GPIO function: 0x00U */
      );
}

void BOARD_InitFlexioCameraPins(void)
{
    CLOCK_EnableClock(kCLOCK_Iomuxc);      /* LPCG on: LPCG is ON. */
    CLOCK_EnableClock(kCLOCK_Iomuxc_Lpsr); /* LPCG on: LPCG is ON. */

    IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_04_LPI2C5_SDA, /* GPIO_LPSR_04 is configured as LPI2C5_SDA */
                     1U);                            /* Software Input On Field: Force input path of pad GPIO_LPSR_04 */
    IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_05_LPI2C5_SCL, /* GPIO_LPSR_05 is configured as LPI2C5_SCL */
                     1U);                            /* Software Input On Field: Force input path of pad GPIO_LPSR_05 */

    /* CSI Interface */
    /* DATA 0-7 */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_24_FLEXIO2_D24, /* GPIO_AD_24 is configured as FLEXIO2_D24 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_25_FLEXIO2_D25, /* GPIO_AD_25 is configured as FLEXIO2_D25 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_26_FLEXIO2_D26, /* GPIO_AD_26 is configured as FLEXIO2_D26 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_27_FLEXIO2_D27, /* GPIO_AD_27 is configured as FLEXIO2_D27 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_28_FLEXIO2_D28, /* GPIO_AD_28 is configured as FLEXIO2_D28 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_29_FLEXIO2_D29, /* GPIO_AD_29 is configured as FLEXIO2_D29 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_30_FLEXIO2_D30, /* GPIO_AD_30 is configured as FLEXIO2_D30 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_31_FLEXIO2_D31, /* GPIO_AD_31 is configured as FLEXIO2_D31 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */

    /* MCLK */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_00_FLEXIO2_D00, /* GPIO_AD_000 is configured as FLEXIO2_D00 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    /* PIXCLK */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_01_FLEXIO2_D01, /* GPIO_AD_01 is configured as FLEXIO2_D01 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    /* HSYNC */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_02_FLEXIO2_D02, /* GPIO_AD_02 is configured as FLEXIO2_D02 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    /* VSYNC */
    IOMUXC_SetPinMux(IOMUXC_GPIO_AD_32_GPIO_MUX3_IO31, /* GPIO_AD_32 is configured as GPIO_MUX3_IO31 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    /* PWDN */
    IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B2_04_GPIO10_IO13, /* GPIO_SD_B2_04 is configured as GPIO10_IO13 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    /* RESET */
    IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_15_GPIO_MUX2_IO25, /* GPIO_SNVS_02 is configured as GPIO13_IO25 */
                     0U); /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_GPR->GPR41 =
        ((IOMUXC_GPR->GPR41 &
          (~(IOMUXC_GPR_GPR41_GPIO_MUX2_GPIO_SEL_HIGH_MASK))) /* Mask bits to zero which are setting */
         | IOMUXC_GPR_GPR41_GPIO_MUX2_GPIO_SEL_HIGH(
               0x00U) /* GPIO2 and CM7_GPIO2 share same IO MUX function, GPIO_MUX2 selects one GPIO function: 0x00U */
        );

    /* Software Input On Field: Input Path is determined by functionality */
    IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_04_LPI2C5_SDA, /* GPIO_SD_B2_10 PAD functional properties : */
                        0x2EU);                         /* PDRV Field: normal drive strength
                                                           Pull Down Pull Up Field: Internal pulldown resistor enabled
                                                           Open Drain Field: Disabled
                                                           Domain write protection: Both cores are allowed
                                                           Domain write protection lock: Neither of DWP bits is locked */
    IOMUXC_SetPinConfig(IOMUXC_GPIO_LPSR_05_LPI2C5_SCL, /* GPIO_SD_B2_11 PAD functional properties : */
                        0x2EU);                         /* PDRV Field: normal drive strength
                                                           Pull Down Pull Up Field: Internal pulldown resistor enabled
                                                           Open Drain Field: Disabled
                                                           Domain write protection: Both cores are allowed
                                                           Domain write protection lock: Neither of DWP bits is locked */
    IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_09_FLEXIO2_D09,  /* GPIO_AD_09 PAD functional properties : */
                        0x04U);                         /* Slew Rate Field: Slow Slew Rate
                                                           Drive Strength Field: normal drive strength
                                                           Pull / Keep Select Field: Pull Enable
                                                           Pull Up / Down Config. Field: Weak pull down
                                                           Open Drain Field: Disabled
                                                           Domain write protection: Both cores are allowed
                                                           Domain write protection lock: Neither of DWP bits is locked */

    /* Set the pins for CSI reset and power down. */
    gpio_pin_config_t pinConfig = {
        kGPIO_DigitalOutput,
        0,
        kGPIO_NoIntmode,
    };

    /* GC0308 Sensor PWDN
     * 0: normal work,
     * 1: standby     */
    pinConfig.outputLogic = 1;
    GPIO_PinInit(BOARD_FLEXIO_CAMERA_PWDN_GPIO, BOARD_FLEXIO_CAMERA_PWDN_PIN, &pinConfig);

    /* GC0308 Sensor Reset
     * 0: chip reset
     * 1: normal work. */
    pinConfig.outputLogic = 1;
    GPIO_PinInit(BOARD_FLEXIO_CAMERA_RESET_GPIO, BOARD_FLEXIO_CAMERA_RESET_PIN, &pinConfig);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
